#+SETUPFILE:../setup/config.setup
#+LANGUAGE:es
#+TITLE: Relación de ejercicios 2: para casa
#+AUTHOR: Ricardo Ruiz Fernández de Alba
#+DESCRIPTION: Doble grado Informática y Matemáticas
#+LATEX_HEADER: \DeclareMathOperator{\Ima}{Im}
#+LATEX_HEADER: \DeclareMathOperator{\R}{\mathbb{R}}

* Ejercicio 4   
*** Enunciado
Sean $A,B$ conjuntos no vacíos de números reales. Supongamos que $a \leq b$
para todo $a \in A$, y para todo $b \in B$.  Prueba que $\sup(A) \leq \inf(B)$.

*** Resolución

De $a\leq b$ se deduce que $a$ es minorante y de $B$ y $b$ mayorante de $A$.
Es decir, que $A$ está mayorado y $B$ está minorado. Por el principio del supremo
y del ínfimo, sean:

$\alpha = \sup(A)$ y $\beta =
\inf(B)$

Como $\alpha$ es el mínimo mayorante:

\[\alpha \leq b \quad \forall b \in B\]

Por tanto $\alpha$ es un minorante de $B$. Pero como $\beta$ es el máximo
minorante: $\alpha \leq \beta$, o, equivalentemente:

\[
\sup(A) \leq \inf(B)
\]

Como se quería demostrar

* Ejercicio 6
Sean $A$ y $B$ conjuntos no vacíos y acotados de números reales. Prueba que

** i) Si $A \subseteq B$, entonces $\sup(A) \leq \sup(B), \quad \inf(A) \geq \inf(B)$.

Como $A$ y $B$ están acotados, por el principio del supremo
e ínfimo sean:

\[
\alpha_a = \inf(A) \quad
\alpha_b = \inf(B) \quad
\beta_a = \sup(A) \quad
\beta_b = \sup(B) \quad
\]

$\beta_b$ es el supremo de $B$, por lo que se verifica que
\[\beta_b \geq b \quad \forall b \in B\]

Como $A$ está contenido en $B$, todo elemento de $A$ pertenece
a $B$, y por tanto:

\[\beta_b \geq a \quad \forall a \in A\]

Pero esto indicaría que $\beta_b$ es un mayorante de $A$. Y como
$\beta_a$ es el mínimo mayorante: $\beta_a \leq \beta_b$,
o, equivalentemente

\[
\sup(A) \leq \sup(B)
\]

Como queríamos demostrar.

De forma análoga:

Como $\alpha_b$ es el ínfimo de $B$, se verifica que
\[
\alpha_b \leq b \quad \forall b \in B
\]

Como $A$ está contenido en $B$, todo elemento de $A$ pertenece
a $B$, y por tanto:
\[
\alpha_b \leq a \quad \forall a \in B
\]

Pero esto indicaría que $\alpha_b$ es un minorante de $A$. Y
como $\alpha_a$ es el máximo minorante: $\alpha_a \geq \alpha_b$,
o, equivalentemente

\[
\inf(A) \geq \inf(B)
\]

Como queríamos demostrar.

En particular, si $A=B$:
\[
\sup(A) = \sup(B) \quad \inf(A) = \inf(B)
\]

** ii) $\sup(A\cup B) = \max\{\sup(A), \sup(B)\}$
*** Demostración propia
Sean

\[C=\{x: x \in A \lor x \in B\}\]
\[\alpha = \sup(A) \quad \beta = \sup(B) \quad \gamma = \sup(C)\]

Como $A \subset C$ y $B \subset C$, utilizando el resultado
anterior obtenemos que:

\begin{align*}
\gamma \geq \alpha \\
\gamma \geq \beta
\end{align*}

Además, como $\alpha$ y $\beta$ son supremos
de $A$ y $B$ respectivamente, se tiene que

\[
\gamma \geq \alpha \geq a \quad \forall a \in A
\]
\[
\gamma \geq \beta \geq b \quad \forall b \in B
\]

Distingamos dos casos:

**** Si $\alpha \geq \beta$, entonces $\alpha = \max\{\alpha,\beta\}$

Como $\alpha \geq \beta \geq b \quad \forall b \in B$, y además $\alpha \geq a \quad \forall a \in A$,
se tiene que
\[
\alpha \geq c \quad \forall c \in C
\]
Y por tanto $\alpha = \gamma$, es decir 

\[
\sup(C) = \sup(A)
\]

**** Si $\beta \geq \alpha$, entonces $\beta = \max\{\alpha,\beta\}$

Como $\beta \geq \alpha \geq a \quad \forall a \in A$, y además  $\beta \geq b \quad \forall b \in B$,
se tiene que
\[
\beta \geq c \quad \forall c \in C
\]

Y por tanto $\beta = \gamma$, es decir
\[
\sup(C) = \sup(B)
\]

Así pues, concluimos que

\[
\sup(A\cup B) = \max\{\sup(A), \sup(B)\}
\]

Como se quería demostrar.

*** Demostración alternativa

Sea $\beta_0 = \max\{\sup(E_1), \sup(E_2)\}$. Tenemos que demostrar
que $\beta_0 = \sup(E_1 \cup E_2)$, es decir que $\beta_0$ es el mínimo
mayorante de $E_1 \cup E_2$.

1) Supongamos $x \in E_1 \cup E_2$, entonces $x \in E_i$ para algún $i \in \{1,2\}$,
y se verifica que:

\[ x \leq \sup(E_i) \leq \max\{\sup(E_1), \sup(E_2)\} = \beta_0 \]

Lo que muestra que $\beta_0$ es un mayorante de $E_1 \cup E_2$.

2) Sea $\beta$ un mayorante de $E_1 \cup E_2$, entonces, se verifica
que $\beta \geq \sup(E_1)$ y que $\beta \geq \sup(E_1)$. Es decir que

\[
\beta \geq \max\{\sup(E_1), \sup(E_2)\} = \beta_0
\]

Por tanto

\[
\beta_0 = \sup(E_1 \cup E_2)
\]

Como queríamos demostrar


* Ejercicio 7

** Enunciado 
Sean $A$ y $B$ conjuntos no vacíos de números reales positivos.
Supongamos que $A$ está mayorado y que $\inf(B) > 0$.
Definamos:

\[
C = \left\{\frac{a}{b}: a \in A, b \in B\right\}
\]

Prueba que $C$ está mayorado y se verica la igualdad:

\[
\sup(C) = \frac{\sup(A)}{\inf(B)}.
\]

** Resolución

Como $A$ está mayorado, sea $\alpha = \sup(A)$, y sea $\beta = \inf(B)$

Por definición de supremo e ínfimo:

\begin{align*}
\alpha \geq a \quad \forall a \in A \\
\beta \leq b \quad \frac{1}{\beta} \geq \frac{1}{b} \quad \forall b \in B
\end{align*}

Como son subconjuntos de números positivos, podemos multiplicar
las desigualdades, obteniendo:

\begin{align}
\frac{\alpha}{\beta} \geq \frac{a}{b} \quad \forall a \in A \quad \forall b \in B
\end{align}

Lo que nos indica que $\frac{\alpha}{\beta}$ es un mayorante de $C$. Por tanto,
$C$ está mayorado. Por el principio del supremo, sea
$\gamma = \sup(C)$. Como $\gamma$ es el mínimo mayorante, se tiene que

\[
\gamma \leq \frac{\alpha}{\beta}
\]

Por otra parte, como $\gamma$ es el supremo de $C$, se tiene
que

\[
\gamma \geq \frac{a}{b} \quad \forall a \in A \quad \forall b \in B
\]

Fijando $a$ y despejando $b$,

\[
b \geq \frac{a}{\gamma} \quad \forall b \in B
\]

De esto se deduce que $\frac{\alpha}{\gamma}$ es un minorante de $B$. Como $\beta$
es el máximo minorante:

\[
\beta \geq \frac{a}{\gamma}
\]

Despejando $a$:

\[
\gamma \beta \geq a \quad \forall a \in A
\]

Y de esto se deduce que $\gamma\beta$ es un mayorante de $A$.
Como $\alpha$ es el mínimo mayorante:

\[
\alpha \leq \gamma \beta
\]

De donde queda que:

\[
\gamma \geq \frac{\alpha}{\beta}
\]

Y por tanto se tiene que $\gamma = \frac{\alpha}{\beta}$, o,
equivalentemente:

\[
\sup(C) = \frac{\sup(A)}{\inf(B)}
\]

Como se quería demostrar

** ¿Qué ocurre si $\inf(B) = 0$?

Entonces, $\beta$ no tendría inverso y, por tanto $C$
no tendría supremo ni estaría mayorado. En particular, se
verificaría que el $\inf(A)=\inf(B)$

* Ejercicio 8
** Enunciado

Sean $A \subset \R$ y $B \subset \R$ conjuntos no vacíos
y supongamos que $\inf(A) > \sup(B)$. Definamos

\[
C = \left\{\frac{1}{a-b}: a \in A, b\in B\right\}
\]

Prueba que:

\[
\sup(C) = \frac{1}{\inf(A)-\sup(B)}
\]

** Resolución

Sean
\[
\alpha = \inf(A); \quad \beta = \sup(B) \quad \alpha > \beta
\] 

Entonces, por definición de ínfimo y supremo, se tiene:

\[a \geq \alpha \quad \forall a \in A\]
\[\beta \geq b \quad \forall b \in B\]

Sumando las desigualdades:

$a+\beta \geq \alpha + b$
$a-b \geq \alpha - \beta$

Pasando a inversos:

\[
\frac{1}{a-b} \leq \frac{1}{\alpha -\beta}
\]

Por tanto, $\frac{1}{\alpha-\beta}$ es un mayorante de $C$. Así,
$C$ está mayorado. Por el principio del supremo,
$\gamma = \sup(C)$. Entonces, es el mínimo mayorante

\[
\gamma \leq \frac{1}{\alpha-\beta}
\]

Por otra parte, por definición

\[
\gamma \geq \frac{1}{a-b} \quad \forall a \in A \quad \forall b \in B
\]


Fijando $b$ y despejando $a$,

\[
a \geq \frac{1}{\gamma} + b
\]
De manera que $\frac{1}{\gamma} + b$ es un minorante de $A$. Como
$\alpha$ es el máximo minorante:

\[
\alpha \geq \frac{1}{\gamma} + b
\]

Despejando $b$:

\[
b \leq \alpha - \frac{1}{\gamma}
\]

Por tanto, $\alpha - \frac{1}{\gamma}$ es un mayorante de $B$.
Como $\beta$ es el mínimo mayorante:

\[
\beta \leq \alpha - \frac{1}{\gamma}
\]

Despejando $\gamma$

\[
\frac{1}{\gamma} \leq \alpha - \beta
\]

Y pasando a inversos

\[
\gamma \geq \frac{1}{\alpha -\beta}
\]


Así pues, $\gamma = \frac{1}{\alpha-\beta}$, o, equivalentemente


\[
\sup(C) = \frac{1}{\inf(A)-\sup(B)}
\]

Como se quería demostrar

* Ejercicio 9

** Enunciado

Sea $A = \left\{ 1 + \frac{1}{n}: n \in \mathbb{N} \right\}$

** Calcula $\inf(A)$ y $\sup(A)$. 

Podemos observar que a medida que $n$ aumenta los elementos
de $A$ son más próximo a $1$. Comprobemos por tanto que
$\alpha = inf A = 1$. 

Por definición de ínfimo:

\[
\forall \varepsilon > 0 \quad \exists x_\varepsilon \in A: \quad  x_\varepsilon < \alpha + \varepsilon
\]

Por tanto, $x_\varepsilon < 1 + \varepsilon$, y como
$x_\varepsilon \in A$ entonces $x_\varepsilon = 1 + \frac{1}{n_\varepsilon}$

Así, se tiene que:

\[
1 + \frac{1}{n_\varepsilon} < 1 + \varepsilon; \quad 
\frac{1}{n_\varepsilon} < \varepsilon
\]

Despejando $n_\varepsilon$:

\[ \frac{1}{\varepsilon} < n_\varepsilon \]

Y esto es cierto $\forall \varepsilon \in \mathbb{R}_0^+ \quad \forall n_\varepsilon \in \mathbb{N}$ , ya que según la propiedad arquimediana,
dado cualquier número real, se verifica que hay números naturales mayores que él.

Por tanto $\inf A=1$

** ¿Y máximo?

Suponiendo que $k=\max A$, entonces por definición:

\[\exists! k:\quad k \geq a \quad \forall a \in A \quad y \quad k \in A\]

Es decir,

\[ k \geq 1 + \frac{1}{n} \quad \forall n \in \mathbb{N} \]

Y como $k \in A$, tiene la forma $1 + \frac{1}{n_k}$,
para un único $n_k \in \mathbb{N}$.

Entonces, se tiene que

\[ 1 + \frac{1}{n_k} \geq 1 + \frac{1}{n}\], de donde se deduce que \(n_k \leq n \quad \forall n \in \mathbb{N} \)

Como el único número natural menor o igual que todos es el $1$.

\[n_k = 1 \Rightarrow k = 1 + \frac{1}{1} = 2\]

Por tanto, $A$ tiene máximo y por tanto, coincide con
el supremo.
\[\sup(A)=\max(A)=2\]

** ¿Tiene $A$ mínimo?
   
Suponiendo que $A$ tuviera mínimo, entonces

\[\min(A) = \inf(A) = 1\]

Y como $\min(A) \in A$:

\[1 + \frac{1}{n_i} = 1\]

Si $\inf A \in A \Rightarrow \min A = \inf A$

Suponiendo que $\inf A \in A$, se tiene que

\[ 1 + \frac{1}{n_i} = 1\]

Pero entonces, $\frac{1}{n_i} = 0$ lo cual es
absurdo $\forall n_i \in \mathbb{N}$, y por
tanto $A$ no tiene mínimo.
