#!/bin/bash
#Hecho por Andrés Millán/Asmilex. Dado el primer argumento, copia los archivos regulares del directorio pasado como primer argumento 
#en otra carpeta, llamada backups. Te pide confirmación para cada archivo
#Voy a ir comentando lo que hace cada cosilla, línea a línea, para que no haya dudas. Creo que a la mayoría le servirá
TestReg=`test -f $ArchEnLista && echo "true "|| echo "false"` 
TestDirec=`test -d $1 && echo "true" || echo "false"`

echo "Se va a hacer una copia de los archivos en $1 llamada backup"

#Comprobaciones preeliminares. El guión termina si los parámetros que se le deben pasar al guión son incorrectos
if [ $TestDirec == false ]; then
    echo "Oh, pero parece que no has introducido un directorio. El guión se va a cerrar"
    exit
fi
if [ "$#" -ne 1 ]; then
    echo "Parece que no has introducido un número correcto de parámetros. El guión se va a cerrar"
    exit
fi
#Fin de comprobaciones preeliminares

mkdir $1/backup 
for archivo in `ls $1`; do 
    echo "Quieres hacer una copia de $archivo? (Y/n)"
    read eleccion
    case $eleccion in
        [Yy])   cp $1/$archivo $1/backup
                echo "Se ha copiado con éxito"
                ;;
        [Nn])   echo "$archivo ha sido ignorado. Continuemos con el siguiente"
                continue;;
    esac
done
echo "La copia ha sido completada satisfactoriamente. Estos son los archivos que hay en el nuevo directorio: "
ls $1/backup

#5,6: variables para comprobar que todo esté correcto. 
#     Funcionan como un booleano: toman el valor "true" si el test es verdad, "false" si no
#22:  <archivo> es una variable a la que se le asigna todo lo que va después de in. 
#     En este caso, como valores de texto (string, cadena de caracteres) de todos los archivos presentes (ls) en el valor pasado como argumento
#24:  Lee en la terminal lo que quieres hacer, si copiar ese archivo o no. Como en cada iteración del bucle el valor de archivo varia, 
#     el echo de la línea 23 cambiará dependiendo del archivo
#25:  Dependiendo de lo que hallamos elegido, se ejecutará [Yy] ó [Nn] (Nota: Lo de antes son expresiones regulares; regex).
#26:  En el primero, lo único que se hace es copiar el archivo seleccionado al directorio de backups, y confirmar que se ha hecho
#29:  En el segundo caso, muestra que se ha ignorado el archivo y continúa con la siguiente iteración del bucle
#30:  continue permite saltarse todo lo que queda de bucle y pasar a la siguiente tanda. Es un poco inútil en este caso, pero eficiente
